routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', function () {
    return view('welcome');
});

Route::get(
    '/home',
    ['uses' => 'HomeController@home', 'as' => 'home']
);

Route::get(
    '/admin/home',
    ['uses' => 'HomeController@home', 'as' => 'admin.home', 'middleware' => 'adminAuth']
);

//*====================================[Routes for Auth]====================================//

Route::group([
    'as' => "auth.",
    'namespace' => "Auth",


], function () {

    Route::get(
        'register',
        'RegisterController@register'
    );
    Route::post(
        'register',
        ['uses' => 'RegisterController@storeUser', 'as' => 'register']
    );

    Route::get(
        'login',
        ['uses' => 'LoginController@login', 'as' => 'login']
    );
    Route::post(
        'login',
        'LoginController@authenticate'
    );
    Route::get(
        'logout',
        ['uses' => 'LoginController@logout', 'as' => 'logout']
    );

    Route::get(
        'forget-password',
        'ForgotPasswordController@getEmail'
    );
    Route::post(
        'forget-password',
        'ForgotPasswordController@postEmail'
    );

    Route::get(
        'reset-password/{token}',
        'ResetPasswordController@getPassword'
    );

    Route::post(
        'reset-password',
        'ResetPasswordController@updatePassword'
    );

    Route::get(
        '/changePassword',
        ['uses' => 'ChangePasswordController@index', 'as' => 'changePassword']
    );
    Route::post(
        '/changePassword',
        ['uses' => 'ChangePasswordController@storeNewPassword', 'as' => 'storeNewPassword']
    );
});
//!====================================[End of Auth]====================================//



//*===================================[Routes for Contact]===================================//

Route::group([
    'as' => "contact.",
    // 'middleware' => "auth"
], function () {

    Route::get(
        '/contacts',
        ['uses' => 'ContactController@index', 'as' => 'index']
    );
    Route::get(
        '/contacts/create',
        ['uses' => 'ContactController@create', 'as' => 'create']
    );
    Route::get(
        '/contacts/{id}',
        ['uses' => 'ContactController@show', 'as' => 'show']
    );
    Route::get(
        '/contacts/edit/{id}',
        ['uses' => 'ContactController@edit', 'as' => 'edit']
    );
    Route::post(
        '/contacts/store',
        ['uses' => 'ContactController@store', 'as' => 'store']
    );
    Route::put(
        '/contacts/update/{id}',
        ['uses' => 'ContactController@update', 'as' => 'update']
    );
    Route::delete(
        '/contacts/delete/{id}',
        ['uses' => 'ContactController@destroy', 'as' => 'destroy']
    );
});
//!===================================[End of Contact]===================================//



//*====================================[Routes for Users]====================================//

Route::group([
    'as' => "user.",
    // 'middleware' => "auth"
], function () {

    Route::get(
        '/users',
        ['uses' => 'UsersController@index', 'as' => 'index']
    );

    Route::get(
        '/users/edit/{id}',
        ['uses' => 'UsersController@edit', 'as' => 'edit']
    );

    Route::post(
        '/users/store/',
        ['uses' => 'UsersController@store', 'as' => 'store']
    );

    Route::PUT(
        '/users/update/{id}',
        ['uses' => 'UsersController@update', 'as' => 'update']
    );

    Route::delete(
        '/users/{id}',
        ['uses' => 'UsersController@destroy', 'as' => 'destroy']
    );
});
//!====================================[End of Users]====================================//



// Route::group([
//     'as' => "customer.",
//     'middleware' => "auth"
// ], function () {

//     Route::get(
//         '/customers',
//         ['uses' => 'CustomerController@index', 'as' => 'index']
//     );

//     Route::get(
//         '/customer/edit/{id}',
//         ['uses' => 'CustomerController@edit', 'as' => 'edit']
//     );

//     Route::post(
//         '/customer/store/',
//         ['uses' => 'CustomerController@store', 'as' => 'store']
//     );

//     Route::PUT(
//         '/customer/update/{id}',
//         ['uses' => 'CustomerController@update', 'as' => 'update']
//     );

//     Route::delete(
//         '/customer/{id}',
//         ['uses' => 'CustomerController@destroy', 'as' => 'destroy']
//     );
// });


Route::group(['middleware' => 'auth'], function () {
    Route::resource('customer', 'CustomerController');
    Route::resource('order', 'OrderController');
});


// Route::group([
//     'as' => "order.",
//     'middleware' => "auth"
// ], function () {

//     Route::get(
//         '/orders',
//         ['uses' => 'OrderController@index', 'as' => 'index']
//     );

//     Route::get(
//         '/users/edit/{id}',
//         ['uses' => 'OrderController@edit', 'as' => 'edit']
//     );

//     Route::post(
//         '/users/store/',
//         ['uses' => 'OrderController@store', 'as' => 'store']
//     );

//     Route::PUT(
//         '/users/update/{id}',
//         ['uses' => 'OrderController@update', 'as' => 'update']
//     );

//     Route::delete(
//         '/users/{id}',
//         ['uses' => 'OrderController@destroy', 'as' => 'destroy']
//     );
// });

resources/views/contacts/create.blade.php
@extends('base')
@section('main')

<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Add a contact</h1>
        <div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            {{ Form::open(['route' => ['contact.store'], 'method' => 'post']) }}
            <div class="form-group">
                <label for="first_name">First Name:</label>
                <input type="text" class="form-control" name="first_name" />
            </div>

            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" class="form-control" name="last_name" />
            </div>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" />
            </div>
            <div class="form-group">
                <label for="city">City:</label>
                <input type="text" class="form-control" name="city" />
            </div>
            <div class="form-group">
                <label for="country">Country:</label>
                <input type="text" class="form-control" name="country" />
            </div>
            <div class="form-group">
                <label for="job_title">Job Title:</label>
                <input type="text" class="form-control" name="job_title" />
            </div>
            <button type="submit" class="btn btn-primary">Add contact</button>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/contacts/edit.blade.php
@extends('base')
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a contact</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
              @endforeach
          </ul>
        </div>
      @endif
      {{ Form::open(['route' => ['contact.update', Crypt::encryptString($contact->id)], 'method' => 'put']) }}
            <div class="form-group">

                <label for="first_name">First Name:</label>
                <input type="text" class="form-control" name="first_name" value={{ $contact->first_name }} />
            </div>

            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" class="form-control" name="last_name" value={{ $contact->last_name }} />
            </div>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" value={{ $contact->email }} />
            </div>
            <div class="form-group">
                <label for="city">City:</label>
                <input type="text" class="form-control" name="city" value={{ $contact->city }} />
            </div>
            <div class="form-group">
                <label for="country">Country:</label>
                <input type="text" class="form-control" name="country" value={{ $contact->country }} />
            </div>
            <div class="form-group">
                <label for="job_title">Job Title:</label>
                <input type="text" class="form-control" name="job_title" value={{ $contact->job_title }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        {{ Form::close() }}
    </div>
</div>
@endsection

resources/views/contacts/index.blade.php
@extends('base')
@section('main')

    <div class="row">
        <div class="col-sm-12">
            <h1 class="display-3">Contacts</h1>
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>First Name</td>
                        <td>Last Name</td>
                        <td>Email</td>
                        <td>Job Title</td>
                        <td>City</td>
                        <td>Country</td>
                        <td colspan="3" style="text-align: center;">Action</td>

                    </tr>
                </thead>
                <tbody>
                    @foreach ($contacts as $row)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $row->first_name }}</td>
                            <td>{{ $row->last_name }}</td>
                            <td>{{ $row->email }}</td>
                            <td>{{ $row->job_title }}</td>
                            <td>{{ $row->city }}</td>
                            <td>{{ $row->country }}</td>
                            <td white-space: pre;>
                                <a href="{{ route('contact.show', Crypt::encryptString($row->id)) }}"
                                    class="btn btn-warning">Show</a>
                            </td>

                            <td>
                                <a href="{{ route('contact.edit', Crypt::encryptString($row->id)) }}"
                                    class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                {{-- <form method="post" action="{{ route('contact.destroy', Crypt::encryptString
                                ($row->id)) }}">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form> --}}

                                {{ Form::open(['route' => ['contact.destroy', Crypt::encryptString($row->id)], 'method' => 'delete']) }}
                                <button type="submit" class="btn btn-danger"
                                    onclick="return confirm('Are you sure you want to delete this record?')">Delete</button>

                                {{ Form::close() }}
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
            <div>
            </div>
        @endsection
        <div class="col-sm-12">

            @if (session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
        <div>
            <a style="margin: 19px;" href="{{ route('contact.create') }}" class="btn btn-primary">New contact</a>
        </div>

resources/views/contacts/show.blade.php
@extends('base')

@section('main')
    <div class="row">
        <div class="col-sm-12">
            <h1 class="display-3">Contacts</h1>
            <table id="example" class="table table-striped table-bordered" style="width:100%">

                <thead>
                    <tr>
                        <td>Firstname:</td>
                        <td>Lastname</td>
                        <td>Email</td>
                        <td>City</td>
                        <td>Country </td>
                        <td>Job Title</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ $contact->first_name }}</td>
                        <td>{{ $contact->last_name }}</td>
                        <td>{{ $contact->email }}</td>
                        <td>{{ $contact->city }}</td>
                        <td>{{ $contact->country }}</td>
                        <td>{{ $contact->job_title }}</td>
                    </tr>






                    </tbody>
            </table>
            <div>
            </div>
        @endsection
        <div class="col-sm-12">

            @if (session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
        <div>
            <a style="margin: 19px;" href="{{ route('contact.create') }}" class="btn btn-primary">New contact</a>
        </div>