routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', function () {
    return view('welcome');
});

Route::get(
    '/home',
    ['uses' => 'HomeController@home', 'as' => 'home']
);

Route::get(
    '/admin/home',
    ['uses' => 'HomeController@home', 'as' => 'admin.home', 'middleware' => 'adminAuth']
);

//*====================================[Routes for Auth]====================================//

Route::group([
    'as' => "auth.",
    'namespace' => "Auth",


], function () {

    Route::get(
        'register',
        'RegisterController@register'
    );
    Route::post(
        'register',
        ['uses' => 'RegisterController@storeUser', 'as' => 'register']
    );

    Route::get(
        'login',
        ['uses' => 'LoginController@login', 'as' => 'login']
    );
    Route::post(
        'login',
        'LoginController@authenticate'
    );
    Route::get(
        'logout',
        ['uses' => 'LoginController@logout', 'as' => 'logout']
    );

    Route::get(
        'forget-password',
        'ForgotPasswordController@getEmail'
    );
    Route::post(
        'forget-password',
        'ForgotPasswordController@postEmail'
    );

    Route::get(
        'reset-password/{token}',
        'ResetPasswordController@getPassword'
    );

    Route::post(
        'reset-password',
        'ResetPasswordController@updatePassword'
    );

    Route::get(
        '/changePassword',
        ['uses' => 'ChangePasswordController@index', 'as' => 'changePassword']
    );
    Route::post(
        '/changePassword',
        ['uses' => 'ChangePasswordController@storeNewPassword', 'as' => 'storeNewPassword']
    );
});
//!====================================[End of Auth]====================================//



//*===================================[Routes for Contact]===================================//

Route::group([
    'as' => "contact.",
    // 'middleware' => "auth"
], function () {

    Route::get(
        '/contacts',
        ['uses' => 'ContactController@index', 'as' => 'index']
    );
    Route::get(
        '/contacts/create',
        ['uses' => 'ContactController@create', 'as' => 'create']
    );
    Route::get(
        '/contacts/{id}',
        ['uses' => 'ContactController@show', 'as' => 'show']
    );
    Route::get(
        '/contacts/edit/{id}',
        ['uses' => 'ContactController@edit', 'as' => 'edit']
    );
    Route::post(
        '/contacts/store',
        ['uses' => 'ContactController@store', 'as' => 'store']
    );
    Route::put(
        '/contacts/update/{id}',
        ['uses' => 'ContactController@update', 'as' => 'update']
    );
    Route::delete(
        '/contacts/delete/{id}',
        ['uses' => 'ContactController@destroy', 'as' => 'destroy']
    );
});
//!===================================[End of Contact]===================================//



//*====================================[Routes for Users]====================================//

Route::group([
    'as' => "user.",
    // 'middleware' => "auth"
], function () {

    Route::get(
        '/users',
        ['uses' => 'UsersController@index', 'as' => 'index']
    );

    Route::get(
        '/users/edit/{id}',
        ['uses' => 'UsersController@edit', 'as' => 'edit']
    );

    Route::post(
        '/users/store/',
        ['uses' => 'UsersController@store', 'as' => 'store']
    );

    Route::PUT(
        '/users/update/{id}',
        ['uses' => 'UsersController@update', 'as' => 'update']
    );

    Route::delete(
        '/users/{id}',
        ['uses' => 'UsersController@destroy', 'as' => 'destroy']
    );
});
//!====================================[End of Users]====================================//



// Route::group([
//     'as' => "customer.",
//     'middleware' => "auth"
// ], function () {

//     Route::get(
//         '/customers',
//         ['uses' => 'CustomerController@index', 'as' => 'index']
//     );

//     Route::get(
//         '/customer/edit/{id}',
//         ['uses' => 'CustomerController@edit', 'as' => 'edit']
//     );

//     Route::post(
//         '/customer/store/',
//         ['uses' => 'CustomerController@store', 'as' => 'store']
//     );

//     Route::PUT(
//         '/customer/update/{id}',
//         ['uses' => 'CustomerController@update', 'as' => 'update']
//     );

//     Route::delete(
//         '/customer/{id}',
//         ['uses' => 'CustomerController@destroy', 'as' => 'destroy']
//     );
// });


Route::group(['middleware' => 'auth'], function () {
    Route::resource('customer', 'CustomerController');
    Route::resource('order', 'OrderController');
});


// Route::group([
//     'as' => "order.",
//     'middleware' => "auth"
// ], function () {

//     Route::get(
//         '/orders',
//         ['uses' => 'OrderController@index', 'as' => 'index']
//     );

//     Route::get(
//         '/users/edit/{id}',
//         ['uses' => 'OrderController@edit', 'as' => 'edit']
//     );

//     Route::post(
//         '/users/store/',
//         ['uses' => 'OrderController@store', 'as' => 'store']
//     );

//     Route::PUT(
//         '/users/update/{id}',
//         ['uses' => 'OrderController@update', 'as' => 'update']
//     );

//     Route::delete(
//         '/users/{id}',
//         ['uses' => 'OrderController@destroy', 'as' => 'destroy']
//     );
// });

resources/views/ajax/customerAjax.blade.php
<script type="text/javascript">
    $(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var customers = $.ajax({
            url: "{{ route('customer.index') }}",
            type: "GET",
            dataType: 'json',
            success: function(response) {
                console.log(response.data);
                return response.data;
            },
            error: function(response) {
                console.log(response.data);
                return response.data;
            }
        });

        var table = $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: customers,
            lengthMenu: [
                [10, 25, 50, 100, -1],
                [10, 25, 50, 100, "All"]
            ],
            columns: [{
                    data: 'id',
                    name: 'id',
                    orderable: false
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'address',
                    name: 'address'
                },
                {
                    data: 'phone_number',
                    name: 'phone_numberorderCustomer'
                },
                {
                    data: 'email',
                    name: 'email'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false,
                }
            ]
        });

        // increment function
        table.on('draw.dt', function() {
            var info = table.page.info();
            table.column(0, {
                search: 'applied',
                order: 'applied',
                page: 'applied'
            }).nodes().each(function(cell, i) {
                cell.innerHTML = i + 1 + info.start;
            });
        });

        // Create function
        $('#createNewCustomer').click(function() {
            $('#c_saveBtn').val("create-customer");
            $('#c_customer_id').val('');
            $('#c_customerForm').trigger("reset");
            $('#c_modelHeading').html("Create New Customer");
            $('#c_ajaxModal').modal('show');

        });

        // Create Save Function
        $('#c_customerForm').on('submit', function(event) {
            event.preventDefault();
            $.ajax({
                data: $('#c_customerForm').serialize(),
                url: "{{ route('customer.store') }}",
                type: "POST",
                dataType: 'JSON',
                success: function(data) {
                    // if (data.errors) {
                    //     $.each(data.errors, function(key, value) {
                    //         if (key == $('#' + key).attr('id')) {
                    //             $('#' + key).addClass('is-invalid')
                    //             $('#error-' + key).text(value)
                    //         }
                    //     })
                    // }
                    if (data.success) {
                        html = '<div class="alert alert-success">' + data.success +
                            '</div>';
                        $('.form-control').removeClass('is-invalid')
                        $('#c_customerForm')[0].reset();
                        $('#c_ajaxModal').modal('hide');
                        table.ajax.reload();
                    }

                },
                error: function(data) {
                    var XHR = $.parseJSON(data.responseText);
                    if (XHR.errors) {
                        $.each(XHR.errors, function(key, value) {
                            if (key == $('#' + key).attr('id')) {
                                $('#' + key).addClass('is-invalid')
                                $('#error-' + key).text(value)
                            }
                        })
                    }
                }
            });
        });

        // Edit function
        $('body').on('click', '.editCustomer', function() {
            var customer_id = $(this).data('id');
            var editData = '{{ route('customer.edit', ':id') }}';
            editUrl = editData.replace(':id', customer_id);
            $.get(editUrl, function(data) {
                console.log(data);
                $('#UpdateModelHeading').html("Edit Customer");
                $('#updateBtn').val("edit-customer");
                $('#UpdateAjaxModal').modal('show');
                $('#u_customer_id').val(data.id);
                $('#u_name').val(data.name);
                $('#u_address').val(data.address);
                $('#u_phone_number').val(data.phone_number);
                $('#u_email').val(data.email);



            })
        });

        // Edit Save Function
        $('#u_customerForm').on('submit', function(event) {
            event.preventDefault();
            var updateCustomerID = $('#u_customer_id').val();
            var updateData = '{{ route('customer.update', ':id') }}';
            updateUrl = updateData.replace(':id', updateCustomerID);
            $.ajax({
                data: $('#u_customerForm').serialize(),
                url: updateUrl,
                type: "PUT",
                dataType: 'JSON',
                success: function(data) {
                    // if (data.errors) {
                    //     $.each(data.errors, function(key, value) {
                    //         if (key == $('#' + key).attr('id')) {
                    //             $('#' + key).addClass('is-invalid')
                    //             $('#error-' + key).text(value)
                    //         }
                    //     })
                    // }
                    if (data.success) {
                        html = '<div class="alert alert-success">' + data.success +
                            '</div>';
                        $('.form-control').removeClass('is-invalid')
                        $('#u_customerForm')[0].reset();
                        $('#UpdateAjaxModal').modal('hide');
                        table.ajax.reload();
                    }

                },
                error: function(data) {
                    var XHR = $.parseJSON(data.responseText);
                    if (XHR.errors) {
                        $.each(XHR.errors, function(key, value) {
                            if (key == $('#' + key).attr('id')) {
                                $('#' + key).addClass('is-invalid')
                                $('#error-' + key).text(value)
                            }
                        })
                    }
                }
            });


        });

        // Delete function
        $('body').on('click', '.deleteCustomer', function() {
            var deleteCustomerID = $(this).data('id');
            var editData = '{{ route('customer.destroy', ':id') }}';
            deleteUrl = editData.replace(':id', deleteCustomerID);
            console.log(deleteCustomerID);

            if (confirm("Are You sure want to delete !")) {
                $.ajax({
                    type: "DELETE",
                    url: deleteUrl,
                    success: function(data) {
                        console.log('Success:', data);
                        table.ajax.reload();

                    },
                    error: function(data) {
                        console.log('Error:', data);
                    }


                });
            }
        });
    });

</script>

resources/views/ajax/orderAjax.blade.php
<script type="text/javascript">
    $(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var customers = $.ajax({
            url: "{{ route('order.index') }}",
            type: "GET",
            dataType: 'json',
            success: function(response) {
                console.log(response.data);
                return response.data;
            },
            error: function(response) {
                console.log(response.data);
                return response.data;
            }
        });

        var table = $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: customers,
            lengthMenu: [
                [10, 25, 50, 100, -1],
                [10, 25, 50, 100, "All"]
            ],
            columns: [{
                    data: 'id',
                    name: 'id',
                    orderable: false
                },
                {
                    data: 'delivery_address',
                    name: 'delivery_address'
                },
                {
                    data: 'phone_number',
                    name: 'phone_number'
                },
                {
                    data: 'package_weight',
                    name: 'package_weight'
                },
                {
                    data: 'dimension',
                    name: 'dimension'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false,
                }
            ]
        });

        // increment function
        table.on('draw.dt', function() {
            var info = table.page.info();
            table.column(0, {
                search: 'applied',
                order: 'applied',
                page: 'applied'
            }).nodes().each(function(cell, i) {
                cell.innerHTML = i + 1 + info.start;
            });
        });

        // Create function
        $('#createNewCustomer').click(function() {
            $('#c_saveBtn').val("create-customer");
            $('#c_order_id').val('');
            $('#c_orderForm').trigger("reset");
            $('#c_modelHeading').html("Create New Customer");
            $('#c_ajaxModal').modal('show');

        });

        // Create Save Function
        $('#c_orderForm').on('submit', function(event) {
            event.preventDefault();
            $.ajax({
                data: $('#c_orderForm').serialize(),
                url: "{{ route('order.store') }}",
                type: "POST",
                dataType: 'JSON',
                success: function(data) {
                    // if (data.errors) {
                    //     $.each(data.errors, function(key, value) {
                    //         if (key == $('#' + key).attr('id')) {
                    //             $('#' + key).addClass('is-invalid')
                    //             $('#error-' + key).text(value)
                    //         }
                    //     })
                    // }
                    if (data.success) {
                        html = '<div class="alert alert-success">' + data.success +
                            '</div>';
                        $('.form-control').removeClass('is-invalid')
                        $('#c_orderForm')[0].reset();
                        $('#c_ajaxModal').modal('hide');
                        table.ajax.reload();
                    }

                },
                error: function(data) {
                    var XHR = $.parseJSON(data.responseText);
                    if (XHR.errors) {
                        $.each(XHR.errors, function(key, value) {
                            if (key == $('#' + key).attr('id')) {
                                $('#' + key).addClass('is-invalid')
                                $('#error-' + key).text(value)
                            }
                        })
                    }
                }
            });
        });

        // Edit function
        $('body').on('click', '.editCustomer', function() {
            var customer_id = $(this).data('id');
            var editData = '{{ route('order.edit', ':id') }}';
            editUrl = editData.replace(':id', customer_id);
            $.get(editUrl, function(data) {
                console.log(data);
                $('#UpdateModelHeading').html("Edit Order");
                $('#u_saveBtn').val("edit-customer");
                $('#UpdateAjaxModal').modal('show');
                $('#u_order_id').val(data.id);
                $('#u_customer').val(data.customer_id);
                $('#u_delivery_address').val(data.delivery_address);
                $('#u_phone_number').val(data.phone_number);
                $('#u_package_weight').val(data.package_weight);
                $('#u_dimension').val(data.dimension);



            })
        });

        // Edit Save Function
        $('#u_orderForm').on('submit', function(event) {
            event.preventDefault();
            var updateCustomerID = $('#u_order_id').val();
            var updateData = '{{ route('order.update', ':id') }}';
            updateUrl = updateData.replace(':id', updateCustomerID);
            $.ajax({
                data: $('#u_orderForm').serialize(),
                url: updateUrl,
                type: "PUT",
                dataType: 'JSON',
                success: function(data) {
                    // if (data.errors) {
                    //     $.each(data.errors, function(key, value) {
                    //         if (key == $('#' + key).attr('id')) {
                    //             $('#' + key).addClass('is-invalid')
                    //             $('#error-' + key).text(value)
                    //         }
                    //     })
                    // }
                    if (data.success) {
                        html = '<div class="alert alert-success">' + data.success +
                            '</div>';
                        $('.form-control').removeClass('is-invalid')
                        $('#u_orderForm')[0].reset();
                        $('#UpdateAjaxModal').modal('hide');
                        table.ajax.reload();
                    }

                },
                error: function(data) {
                    var XHR = $.parseJSON(data.responseText);
                    if (XHR.errors) {
                        $.each(XHR.errors, function(key, value) {
                            if (key == $('#' + key).attr('id')) {
                                $('#' + key).addClass('is-invalid')
                                $('#error-' + key).text(value)
                            }
                        })
                    }
                }
            });


        });

        // Delete function
        $('body').on('click', '.deleteOrder', function() {
            var deleteOrderID = $(this).data('id');
            var editData = '{{ route('order.destroy', ':id') }}';
            deleteUrl = editData.replace(':id', deleteOrderID);
            console.log(deleteOrderID);

            if (confirm("Are You sure want to delete !")) {
                $.ajax({
                    type: "DELETE",
                    url: deleteUrl,
                    success: function(data) {
                        console.log('Success:', data);
                        table.ajax.reload();

                    },
                    error: function(data) {
                        console.log('Error:', data);
                    }


                });
            }
        });
    });
</script>